---
- hosts: all
  become: true
  pre_tasks:

  - name: install updates RedHat
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == 'RedHat'
  
  - name: install updates Ubuntu
    apt: 
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == 'Ubuntu'

- hosts: ubuntu_servers
  become: true
  tasks:

  - name: Install Apache2 and php package for Ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == 'Ubuntu'

  - name: Install Apache2 and php package for RedHat
    dnf:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == 'RedHat'

- hosts: all
  become: true
  tasks:

  - name: create ansible user 
    user:
      name: ansible
      groups: root
  
  - name: add ssh key for ansible user
    authorized_key:
      user: ansible
      state: present
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAf6d+4AOmSbUQOyIv85bJ9qFdkQaFnVsmKJYHV4OfYl ansible.testing"
  
  - name: add sudoers file for ansible user
    copy:
      src: sudoer_ansible
      dest: /etc/sudoers.d/ansible
      owner: root
      group: root
      mode: '0440'
  